
kafka:
  bootstrap-servers: 10.5.6.3:10209
  consumer:
    enbale-auto-commit: true
    commit-interval: 100
    auto-offset-reset: earliest
#    session-timeout: 6000
    topic: SensefacePush
    groupid: lala
    concurrency: 1
  producer:
    server: 10.5.6.3:10209
    retries: 0
    batch-size: 4096
    linger: 1
    buffer-memory: 40960

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://10.5.6.3:10208/senseface?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp



